#!/bin/bash
#
# A u2up-yocto instalation/upgrade dialog library
#
#set -xe

U2UP_INSTALL_DIALOG_LIB_SOURCED=yes

display_net_config_submenu() {
	local conf_dir=${1}
	local current_set=""
	local current_item=""
	local net_internal_ifname_current=""
	local net_internal_addr_mask_current=${2:-"192.168.1.1/24"}
	local net_internal_gw_current=${3:-"192.168.1.1"}
	local net_dns_current=${4:-"192.168.1.1"}
	local net_domains_current=${5:-"local.net"}
	local rv=1

	check_net_internal_ifname_set
	rv=$?
	if [ $rv -ne 0 ]; then
		return $rv
	fi
	local net_internal_ifname_current=$u2up_NET_INTERNAL_IFNAME

	while true; do
		exec 3>&1
		selection=$(IFS='|'; \
		dialog \
			--backtitle "${U2UP_BACKTITLE}" \
			--title "Network configuration [${net_internal_ifname_current}]" \
			--clear \
			--default-item "$current_item" \
			--cancel-label "Cancel" \
			--extra-label "Change" \
			--cr-wrap \
			--inputmenu "\nPlease set:" $HEIGHT 0 12 \
			"IP address/mask:" ${net_internal_addr_mask_current} \
			"IP gateway:" ${net_internal_gw_current} \
			"DNS:" ${net_dns_current} \
			"Domains:" ${net_domains_current} \
		2>&1 >&3)
		exit_status=$?
		exec 3>&-

		case $exit_status in
		$DIALOG_CANCEL|$DIALOG_ESC)
			clear
			echo "Return from submenu." >&2
			return 1
			;;
		esac

		current_item="$(get_item_selection $selection)"
		current_set="$(save_u2up_net_config_selection ${conf_dir} $selection)"
		if [ -n "$current_set" ]; then
			#Resize pressed: set new dialog values
			eval $current_set
		else
			#Ok
			save_u2up_net_config_selection ${conf_dir} "IP address/mask: ${net_internal_addr_mask_current}"
			(( rv+=$? ))
			save_u2up_net_config_selection ${conf_dir} "IP gateway: ${net_internal_gw_current}"
			(( rv+=$? ))
			save_u2up_net_config_selection ${conf_dir} "DNS: ${net_dns_current}"
			(( rv+=$? ))
			save_u2up_net_config_selection ${conf_dir} "Domains: ${net_domains_current}"
			(( rv+=$? ))
			return $rv
		fi
	done
}

