#!/bin/bash
#
# A u2up-yocto instalation/upgrade dialog library
#
#set -xe

U2UP_INSTALL_DIALOG_LIB_SOURCED=yes

display_target_hostname_submenu() {
	local current_set=""
	local current_item=""
	local conf_dir=${1}
	local target_hostname_current=${2:-"$(hostname)"}
	local rv=0

	while true; do
		exec 3>&1
		selection=$(IFS='|'; \
		dialog \
			--backtitle "${U2UP_BACKTITLE}" \
			--title "Hostname configuration [${target_hostname_current}]" \
			--clear \
			--default-item "$current_item" \
			--cancel-label "Cancel" \
			--extra-label "Change" \
			--cr-wrap \
			--inputmenu "\nPlease set:" $HEIGHT 0 6 \
			"Hostname:" ${target_hostname_current} \
		2>&1 1>&3)
		exit_status=$?
		exec 3>&-

		case $exit_status in
		$DIALOG_CANCEL|$DIALOG_ESC)
			clear
			echo "Return from submenu." >&2
			return 1
			;;
		esac

		current_item="$(get_item_selection $selection)"
		current_set="$(save_u2up_target_hostname_selection ${conf_dir} $selection)"
		if [ -n "$current_set" ]; then
			#Resize pressed: set new dialog values
			eval $current_set
		else
			#Ok
			save_u2up_target_hostname_selection ${conf_dir} "Hostname: ${target_hostname_current}"
			(( rv+=$? ))
			return $rv
		fi
	done
}

display_target_admin_submenu() {
	local current_set=""
	local current_item=""
	local conf_dir=${1}
	local target_admin_name_current=${2:-"admin"}
	local rv=0

	while true; do
		exec 3>&1
		selection=$(IFS='|'; \
		dialog \
			--backtitle "${U2UP_BACKTITLE}" \
			--title "Hostname configuration [${target_admin_name_current}]" \
			--clear \
			--default-item "$current_item" \
			--cancel-label "Cancel" \
			--extra-label "Change" \
			--cr-wrap \
			--inputmenu "\nPlease set:" $HEIGHT 0 6 \
			"Admin name:" ${target_admin_name_current} \
		2>&1 1>&3)
		exit_status=$?
		exec 3>&-

		case $exit_status in
		$DIALOG_CANCEL|$DIALOG_ESC)
			clear
			echo "Return from submenu." >&2
			return 1
			;;
		esac

		current_item="$(get_item_selection $selection)"
		current_set="$(save_u2up_target_admin_selection ${conf_dir} $selection)"
		if [ -n "$current_set" ]; then
			#Resize pressed: set new dialog values
			eval $current_set
		else
			#Ok
			save_u2up_target_admin_selection ${conf_dir} "Admin name: ${target_admin_name_current}"
			(( rv+=$? ))
			return $rv
		fi
	done
}

display_net_external_ifname_submenu() {
	local conf_dir=${1}
	local net_external_ifname_current=${2}
	local radiolist=""
	local tag="start_tag"
	local ifname=""
	local mac=""
	local none=""

	if [ -f "${conf_dir}/${U2UP_NETWORK_INTERNAL_CONF_FILE}" ]; then
		source ${conf_dir}/${U2UP_NETWORK_INTERNAL_CONF_FILE}
	fi
	if [ -z "${net_external_ifname_current}" ]; then
		none="on"
	else
		none="off"
	fi
	radiolist=$(ip link | grep "BROADCAST,MULTICAST" | sed 's/[0-9]*: //' | sed 's/: .*//g' | while read ifname; do
		if [ -n "$ifname" ] && [ "$ifname" != "$u2up_NET_INTERNAL_IFNAME" ] && [[ "$ifname" != "$tag"* ]]; then
			if [ "${tag}" == "start_tag" ]; then
				echo -n "none|-|${none}|"
			fi
			tag=$ifname
			mac="$(ip link show dev $ifname | grep "link\/ether" | sed 's/ *link\/ether *//' | sed 's/ .*//')"
			if [ -n "$net_external_ifname_current" ] && [ "$tag" == "$net_external_ifname_current" ]; then
				echo -n "${tag}|"$mac"|on|"
			else
				echo -n "${tag}|"$mac"|off|"
			fi
		fi
	done)

	exec 3>&1
	selection=$(IFS='|'; \
	dialog \
		--backtitle "${U2UP_BACKTITLE}" \
		--title "Network external interface selection" \
		--clear \
		--cancel-label "Cancel" \
		--radiolist "Please select:" $HEIGHT $WIDTH 0 \
		${radiolist} \
	2>&1 1>&3)
	exit_status=$?
	exec 3>&-

	case $exit_status in
	$DIALOG_CANCEL|$DIALOG_ESC)
		clear
		echo "Return from submenu." >&2
		return 0
		;;
	esac

	mac="$(ip link show dev $selection | grep "link\/ether" | sed 's/ *link\/ether *//' | sed 's/ .*//')"
	save_u2up_net_external_iface_selection $selection ${conf_dir}
	save_u2up_net_external_mac_selection $mac ${conf_dir}
}

display_net_internal_ifname_submenu() {
	local conf_dir=${1}
	local net_internal_ifname_current=${2}
	local radiolist=""
	local tag="start_tag"
	local ifname=""
	local mac=""
	local none=""

	if [ -f "${conf_dir}/${U2UP_NETWORK_EXTERNAL_CONF_FILE}" ]; then
		source ${conf_dir}/${U2UP_NETWORK_EXTERNAL_CONF_FILE}
	fi
	if [ -z "${net_internal_ifname_current}" ]; then
		none="on"
	else
		none="off"
	fi
	radiolist=$(ip link | grep "BROADCAST,MULTICAST" | sed 's/[0-9]*: //' | sed 's/: .*//g' | while read ifname; do
		if [ -n "$ifname" ] && [ "$ifname" != "$u2up_NET_EXTERNAL_IFNAME" ] && [[ "$ifname" != "$tag"* ]]; then
			if [ "${tag}" == "start_tag" ]; then
				echo -n "none|-|${none}|"
			fi
			tag=$ifname
			mac="$(ip link show dev $ifname | grep "link\/ether" | sed 's/ *link\/ether *//' | sed 's/ .*//')"
			if [ -n "$net_internal_ifname_current" ] && [ "$tag" == "$net_internal_ifname_current" ]; then
				echo -n "${tag}|"$mac"|on|"
			else
				echo -n "${tag}|"$mac"|off|"
			fi
		fi
	done)

	exec 3>&1
	selection=$(IFS='|'; \
	dialog \
		--backtitle "${U2UP_BACKTITLE}" \
		--title "Network internal interface selection" \
		--clear \
		--cancel-label "Cancel" \
		--radiolist "Please select:" $HEIGHT $WIDTH 0 \
		${radiolist} \
	2>&1 1>&3)
	exit_status=$?
	exec 3>&-

	case $exit_status in
	$DIALOG_CANCEL|$DIALOG_ESC)
		clear
		echo "Return from submenu." >&2
		return 0
		;;
	esac

	mac="$(ip link show dev $selection | grep "link\/ether" | sed 's/ *link\/ether *//' | sed 's/ .*//')"
	save_u2up_net_internal_iface_selection $selection ${conf_dir}
	save_u2up_net_internal_mac_selection $mac ${conf_dir}
}

display_net_external_config_submenu() {
	local conf_dir=${1}
	local current_set=""
	local current_item=""
	local net_external_ifname_current=""
	local net_external_mac_addr_current=${2}
	local net_external_addr_mask_current=${3:-"192.168.1.1/24"}
	local net_external_gw_current=${4:-"192.168.1.1"}
	local net_external_dns1_current=${5:-"192.168.1.1"}
	local net_external_dns2_current=${6:-"192.168.1.1"}
	local rv=1

	check_net_external_ifname_set $conf_dir
	rv=$?
	if [ $rv -ne 0 ]; then
		display_result "Network external interface check" "Please select your network external interface!"
		return $rv
	fi
	local net_external_ifname_current=$u2up_NET_EXTERNAL_IFNAME

	while true; do
		exec 3>&1
		selection=$(IFS='|'; \
		dialog \
			--backtitle "${U2UP_BACKTITLE}" \
			--title "Network configuration [${net_external_ifname_current}]" \
			--clear \
			--default-item "$current_item" \
			--cancel-label "Cancel" \
			--extra-label "Change" \
			--cr-wrap \
			--inputmenu "\nPlease set:" $HEIGHT 0 14 \
			"MAC address:" "${net_external_mac_addr_current}" \
			"IP address/mask:" ${net_external_addr_mask_current} \
			"IP gateway:" ${net_external_gw_current} \
			"DNS1:" ${net_external_dns1_current} \
			"DNS2:" ${net_external_dns2_current} \
		2>&1 >&3)
		exit_status=$?
		exec 3>&-

		case $exit_status in
		$DIALOG_CANCEL|$DIALOG_ESC)
			clear
			echo "Return from submenu." >&2
			return 1
			;;
		esac

		current_item="$(get_item_selection $selection)"
		current_set="$(save_u2up_net_external_config_selection ${conf_dir} $selection)"
		if [ -n "$current_set" ]; then
			#Resize pressed: set new dialog values
			eval $current_set
		else
			#Ok
			save_u2up_net_external_config_selection ${conf_dir} "MAC address: ${net_external_mac_addr_current}"
			(( rv+=$? ))
			save_u2up_net_external_config_selection ${conf_dir} "IP address/mask: ${net_external_addr_mask_current}"
			(( rv+=$? ))
			save_u2up_net_external_config_selection ${conf_dir} "IP gateway: ${net_external_gw_current}"
			(( rv+=$? ))
			save_u2up_net_external_config_selection ${conf_dir} "DNS1: ${net_external_dns1_current}"
			(( rv+=$? ))
			save_u2up_net_external_config_selection ${conf_dir} "DNS2: ${net_external_dns2_current}"
			(( rv+=$? ))
			return $rv
		fi
	done
}

display_net_internal_config_submenu() {
	local conf_dir=${1}
	local current_set=""
	local current_item=""
	local net_internal_ifname_current=""
	local net_internal_mac_addr_current=${2}
	local net_internal_addr_mask_current=${3:-"192.168.1.1/24"}
	local net_internal_gw_current=${4:-"192.168.1.1"}
	local rv=1

	check_net_external_ifname_set $conf_dir
	rv=$?
	if [ $rv -ne 0 ]; then
		display_result "Network external interface check" "Please select your network external interface!"
		return $rv
	fi
	local net_internal_ifname_current=$u2up_NET_INTERNAL_IFNAME

	while true; do
		exec 3>&1
		selection=$(IFS='|'; \
		dialog \
			--backtitle "${U2UP_BACKTITLE}" \
			--title "Network configuration [${net_internal_ifname_current}]" \
			--clear \
			--default-item "$current_item" \
			--cancel-label "Cancel" \
			--extra-label "Change" \
			--cr-wrap \
			--inputmenu "\nPlease set:" $HEIGHT 0 14 \
			"MAC address:" "${net_internal_mac_addr_current}" \
			"IP address/mask:" ${net_internal_addr_mask_current} \
			"IP gateway:" ${net_internal_gw_current} \
		2>&1 >&3)
		exit_status=$?
		exec 3>&-

		case $exit_status in
		$DIALOG_CANCEL|$DIALOG_ESC)
			clear
			echo "Return from submenu." >&2
			return 1
			;;
		esac

		current_item="$(get_item_selection $selection)"
		current_set="$(save_u2up_net_internal_config_selection ${conf_dir} $selection)"
		if [ -n "$current_set" ]; then
			#Resize pressed: set new dialog values
			eval $current_set
		else
			#Ok
			save_u2up_net_internal_config_selection ${conf_dir} "MAC address: ${net_internal_mac_addr_current}"
			(( rv+=$? ))
			save_u2up_net_internal_config_selection ${conf_dir} "IP address/mask: ${net_internal_addr_mask_current}"
			(( rv+=$? ))
			save_u2up_net_internal_config_selection ${conf_dir} "IP gateway: ${net_internal_gw_current}"
			(( rv+=$? ))
			save_u2up_net_internal_config_selection ${conf_dir} "DNS: ${net_dns_current}"
			(( rv+=$? ))
			save_u2up_net_internal_config_selection ${conf_dir} "Domains: ${net_domains_current}"
			(( rv+=$? ))
			return $rv
		fi
	done
}

