#!/bin/bash
#
# A dialog menu based u2up-pc-installer program
#
#set -xe

U2UP_CONF_DIR="/etc/u2up-conf.d"
if [ ! -d "${U2UP_CONF_DIR}" ]; then
	rm -rf $U2UP_CONF_DIR
	mkdir -p $U2UP_CONF_DIR
fi

U2UP_IDS_CONF_FILE="00-u2up_ids-conf"
U2UP_KEYMAP_CONF_FILE="10-keymap-conf"
U2UP_TARGET_DISK_CONF_FILE="20-target_disk-conf"
U2UP_TARGET_HOSTNAME_CONF_FILE="30-hostname-conf"
U2UP_TARGET_ADMIN_CONF_FILE="40-admin-conf"
U2UP_NETWORK_CONF_FILE="50-network-conf"
U2UP_INSTALL_REPO_CONF_FILE="60-install_repo-conf"

U2UP_TEMP_DIR="/tmp/u2up-temp"
if [ ! -d "${U2UP_TEMP_DIR}" ]; then
	rm -rf $U2UP_TEMP_DIR
	mkdir -p $U2UP_TEMP_DIR
fi
U2UP_TARGET_DISK_SFDISK_BASH=${U2UP_TEMP_DIR}/u2up_target_disk-sfdisk_bash
U2UP_TARGET_DISK_SFDISK_DUMP=${U2UP_TEMP_DIR}/u2up_target_disk-sfdisk_dump

PART_TYPE_EFI="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
PART_TYPE_LINUX="0FC63DAF-8483-4772-8E79-3D69D8477DE4"

get_boot_label() {
	local boot_label=$1
	local boot_label_conf=
	if [ -z "${boot_label}" ]; then
		return
	fi
	boot_label_conf="/boot/loader/entries/${boot_label}.conf"
	if [ ! -f "${boot_label_conf}" ]; then
		return
	fi
	cat ${boot_label_conf} | grep title | sed 's/.*title[ ]*//g'
}

get_default_boot_label() {
	local default_boot_conf=""
	if [ ! -f "/boot/loader/loader.conf" ]; then
		return
	fi
	default_boot_conf="/boot/loader/entries/$(cat /boot/loader/loader.conf | grep "default" | sed 's/default //g').conf"
	if [ ! -f "${default_boot_conf}" ]; then
		return
	fi
	cat ${default_boot_conf} | grep title | sed 's/.*title[ ]*//g'
}

set_default_boot() {
	local new_boot_label=$1

	if [ -z "${new_boot_label}" ]; then
		return 1
	fi
	if [ ! -f "/boot/loader/entries/${new_boot_label}.conf" ]; then
		return 1
	fi
	echo "default ${new_boot_label}" > /boot/loader/loader.conf
	(( rv+=$? ))
	echo "timeout 5" >> /boot/loader/loader.conf
	(( rv+=$? ))
	if [ $rv -ne 0 ]; then
		return $rv
	fi
	return $rv
}

get_current_target_disk() {
	if [ -f "${U2UP_CONF_DIR}/${U2UP_TARGET_DISK_CONF_FILE}" ]; then
		source $U2UP_CONF_DIR/$U2UP_TARGET_DISK_CONF_FILE
		echo -n "${TARGET_DISK_SET}"
	fi
}

get_current_target_part() {
	if [ -f "${U2UP_CONF_DIR}/${U2UP_TARGET_DISK_CONF_FILE}" ]; then
		source $U2UP_CONF_DIR/$U2UP_TARGET_DISK_CONF_FILE
		echo -n "${TARGET_PART_SET}"
	fi
}

get_root_label_suffix() {
	local target_disk=$1
	local target_part=$2
	if [ -n "${target_part}" ]; then
		case ${target_part} in
		${target_disk}3)
			echo "A"
			return 0
			;;
		${target_disk}4)
			echo "B"
			return 0
			;;
		esac
	fi
	return 1
}

get_root_label_from_suffix() {
	local label_suffix=$1
	if [ -n "${label_suffix}" ]; then
		case ${label_suffix} in
		A|B)
			echo -n "root${label_suffix}"
			return 0
			;;
		esac
	fi
	return 1
}

get_root_label_suffix_from_label() {
	local label=$1
	if [ -n "${label}" ]; then
		case ${label} in
		rootA)
			echo "A"
			return 0
			;;
		rootB)
			echo "B"
			return 0
			;;
		esac
	fi
	return 1
}

get_root_label() {
	local label=""
	local target_disk=$1
	local target_part=$2
	local label_suffix="$(get_root_label_suffix ${target_disk} ${target_part})"
	if [ -n "${label_suffix}" ]; then
		label="$(get_root_label_from_suffix ${label_suffix})"
		if [ -n "${label}" ]; then
			echo -n "${label}"
			return 0
		fi
	fi
	return 1
}

set_target_done_for() {
	local file=${1}
	local new_target_done=${2:-0}
	local rv=1
	if [ -z "$file" ] || [ ! -e "$file" ]; then
		return $rv
	fi
	cat ${file} | grep -v "TARGET_DONE=" > ${file}_tmp
	rv=$?
	echo "TARGET_DONE=${new_target_done}" >> ${file}_tmp
	(( rv+=$? ))
	mv ${file}_tmp ${file}
	(( rv+=$? ))
	return $rv
}

store_keymap_selection() {
	local rv=1
	local keymap=$1
	local conf_dir=${2:-${U2UP_CONF_DIR}}

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ -n "$keymap" ]; then
		loadkeys -p $keymap 2> /dev/null
		rv=$?
		if [ $rv -eq 0 ]; then
			echo "KEYMAP_SET=$keymap" > ${conf_dir}/${U2UP_KEYMAP_CONF_FILE}
			echo "TARGET_DONE=0" >> ${conf_dir}/${U2UP_KEYMAP_CONF_FILE}
		fi
	fi
	return $rv
}

enable_keymap_selection() {
	local rv=1
	local KEYMAP_SET=""
	local TARGET_DONE=0
	local new_target_done=${1:-0}
	local root_path_prefix=${2:-"/"}
	local conf_dir=${3:-${U2UP_CONF_DIR}}

	if [ "${root_path_prefix}" = "/" ]; then
		root_path_prefix=""
	fi

	if [ ! -f "${root_path_prefix}${conf_dir}/${U2UP_KEYMAP_CONF_FILE}" ]; then
		return 1
	fi
	source ${root_path_prefix}${conf_dir}/${U2UP_KEYMAP_CONF_FILE}
	if [ -n "$KEYMAP_SET" ] && [ $TARGET_DONE -eq 0 ]; then
		loadkeys $KEYMAP_SET
		rv=$?
		if [ $rv -eq 0 ]; then
			echo "KEYMAP=$KEYMAP_SET" > ${root_path_prefix}/etc/vconsole.conf
			set_target_done_for ${root_path_prefix}${conf_dir}/${U2UP_KEYMAP_CONF_FILE} ${new_target_done}
			rv=$?
		fi
	fi
	return $rv
}

store_target_disk_selection() {
	local rv=1
	local disk=$1
	local conf_dir=${2:-${U2UP_CONF_DIR}}

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	cat ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE} | grep -v "TARGET_DISK_SET=" > ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp
	if [ -n "$disk" ]; then
		echo "TARGET_DISK_SET=$disk" >> ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp
	else
		return 1
	fi
	mv ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}
	rv=$?
	return $rv
}

store_target_part_selection() {
	local rv=1
	local part=$1
	local conf_dir=${2:-${U2UP_CONF_DIR}}

	cat ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE} | grep -v "TARGET_PART_SET=" > ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp
	if [ -n "$part" ]; then
		echo "TARGET_PART_SET=$part" >> ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp
	else
		return 1
	fi
	mv ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}
	rv=$?
	return $rv
}

store_target_partsize_selection() {
	local rv=1
	local var_target_partsz_set=""
	local var_target_partsz_current=""
	local conf_dir=${1}
	shift
	local part=$(echo $@ | sed 's/RENAMED //' | sed 's/ .*//')
	declare -i part_size=$(echo $@ | sed 's/.*://')

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ $part_size -le 0 ]; then
		return 1
	fi
	case $part in
	boot)
		var_target_partsz_set=TARGET_BOOT_PARTSZ_SET
		var_target_partsz_current=target_boot_partsz_current
		;;
	log)
		var_target_partsz_set=TARGET_LOG_PARTSZ_SET
		var_target_partsz_current=target_log_partsz_current
		;;
	rootA)
		var_target_partsz_set=TARGET_ROOTA_PARTSZ_SET
		var_target_partsz_current=target_rootA_partsz_current
		;;
	rootB)
		var_target_partsz_set=TARGET_ROOTB_PARTSZ_SET
		var_target_partsz_current=target_rootB_partsz_current
		;;
	*)
		return 1;
	esac

	cat ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE} | grep -v "${var_target_partsz_set}=" > ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp
	echo "${var_target_partsz_set}=$part_size" >> ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp
	mv ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}_tmp ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}
	rv=$?
	echo "${var_target_partsz_current}=${part_size}"
	return $rv
}

store_net_internal_iface_selection() {
	local rv=1
	local ifname=$1
	local conf_dir=${2:-${U2UP_CONF_DIR}}

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	cat ${conf_dir}/${U2UP_NETWORK_CONF_FILE} | grep -v "NET_INTERNAL_IFNAME_SET=" > ${conf_dir}/${U2UP_NETWORK_CONF_FILE}_tmp
	if [ -n "$ifname" ]; then
		echo "NET_INTERNAL_IFNAME_SET=$ifname" >> ${conf_dir}/${U2UP_NETWORK_CONF_FILE}_tmp
	else
		return 1
	fi
	mv ${conf_dir}/${U2UP_NETWORK_CONF_FILE}_tmp ${conf_dir}/${U2UP_NETWORK_CONF_FILE}
	rv=$?
	return $rv
}

store_target_hostname_selection() {
	local rv=1
	local var_target_hostname_set=""
	local var_target_hostname_current=""
	local conf_dir=${1}
	shift
	local value="$(echo $@ | sed 's/[^:]*://' | sed 's/ *//')"
	local name="$(echo $@ | sed 's/RENAMED //' | sed 's/:.*//')"

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ -z "${value}" ] || [ "x${name}" = "x${value}" ]; then
		return 0
	fi
	case $name in
	"Hostname")
		var_target_hostname_set=TARGET_HOSTNAME_SET
		var_target_hostname_current=target_hostname_current
		;;
	*)
		return 1;
	esac

	cat ${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE} | grep -v "${var_target_hostname_set}=" > ${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}_tmp
	echo "${var_target_hostname_set}=$value" >> ${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}_tmp
	mv ${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}_tmp ${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}
	rv=$?
	echo "${var_target_hostname_current}=${value}"
	return $rv
}

enable_target_hostname_selection() {
	local rv=1
	local TARGET_HOSTNAME_SET=""
	local TARGET_DONE=0
	local new_target_done=${1:-0}
	local root_path_prefix=${2:-"/"}
	local conf_dir=${3:-${U2UP_CONF_DIR}}

	if [ "${root_path_prefix}" = "/" ]; then
		root_path_prefix=""
	fi

	if [ ! -f "${root_path_prefix}${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}" ]; then
		return 1
	fi
	source ${root_path_prefix}${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}
	if [ -n "$TARGET_HOSTNAME_SET" ] && [ $TARGET_DONE -eq 0 ]; then
		hostnamectl set-hostname $TARGET_HOSTNAME_SET
		rv=$?
		if [ $rv -eq 0 ]; then
			set_target_done_for ${root_path_prefix}${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE} ${new_target_done}
			rv=$?
		fi
	fi
	return $rv
}

store_target_admin_selection() {
	local rv=1
	local var_target_admin_name_set=""
	local var_target_admin_name_current=""
	local conf_dir=${1}
	shift
	local value="$(echo $@ | sed 's/[^:]*://' | sed 's/ *//')"
	local name="$(echo $@ | sed 's/RENAMED //' | sed 's/:.*//')"

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ -z "${value}" ] || [ "x${name}" = "x${value}" ]; then
		return 0
	fi
	case $name in
	"Admin name")
		var_target_admin_name_set=TARGET_ADMIN_NAME_SET
		var_target_admin_name_current=target_admin_name_current
		;;
	*)
		return 1;
	esac

	cat ${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE} | grep -v "${var_target_admin_name_set}=" > ${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}_tmp
	echo "${var_target_admin_name_set}=$value" >> ${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}_tmp
	mv ${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}_tmp ${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}
	rv=$?
	echo "${var_target_admin_name_current}=${value}"
	return $rv
}

enable_target_admin_selection() {
	local rv=1
	local TARGET_ADMIN_NAME_SET=""
	local TARGET_DONE=0
	local new_target_done=${1:-0}
	local root_path_prefix=${2:-"/"}
	local conf_dir=${3:-${U2UP_CONF_DIR}}

	if [ "${root_path_prefix}" = "/" ]; then
		root_path_prefix=""
	fi

	if [ ! -f "${root_path_prefix}${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}" ]; then
		return 1
	fi
	source ${root_path_prefix}${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}
	if [ -n "$TARGET_ADMIN_NAME_SET" ] && [ $TARGET_DONE -eq 0 ]; then
		useradd -m -c "Admin User" $TARGET_ADMIN_NAME_SET
		rv=$?
		if [ $rv -ne 0 ] && [ $rv -ne 9 ]; then
			return 1
		fi
		passwd -de $TARGET_ADMIN_NAME_SET
		rv=$?
		if [ $rv -ne 0 ]; then
			return 1
		fi
		usermod -aG wheel $TARGET_ADMIN_NAME_SET
		rv=$?
		if [ $rv -ne 0 ]; then
			return 1
		fi
		# Locking the root account and scrambling its password!
		passwd -l root
		rv=$?
		if [ $rv -ne 0 ]; then
			return 1
		fi
		usermod -p '!' root
		rv=$?
		if [ $rv -eq 0 ]; then
			set_target_done_for ${root_path_prefix}${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE} ${new_target_done}
			rv=$?
		fi
	fi
	return $rv
}

store_net_config_selection() {
	local rv=1
	local var_net_config_set=""
	local var_net_config_current=""
	local conf_dir=${1}
	shift
	local value="$(echo $@ | sed 's/[^:]*://' | sed 's/ *//')"
	local name="$(echo $@ | sed 's/RENAMED //' | sed 's/:.*//')"

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ -z "${value}" ] || [ "x${name}" = "x${value}" ]; then
		return 0
	fi
	case $name in
	"IP address/mask")
		var_net_config_set=NET_INTERNAL_ADDR_MASK_SET
		var_net_config_current=net_internal_addr_mask_current
		;;
	"IP gateway")
		var_net_config_set=NET_INTERNAL_GW_SET
		var_net_config_current=net_internal_gw_current
		;;
	"DNS")
		var_net_config_set=NET_DNS_SET
		var_net_config_current=net_dns_current
		;;
	"Domains")
		var_net_config_set=NET_DOMAINS_SET
		var_net_config_current=net_domains_current
		;;
	*)
		return 1;
	esac

	cat ${conf_dir}/${U2UP_NETWORK_CONF_FILE} | grep -v "${var_net_config_set}=" > ${conf_dir}/${U2UP_NETWORK_CONF_FILE}_tmp
	echo "${var_net_config_set}=$value" >> ${conf_dir}/${U2UP_NETWORK_CONF_FILE}_tmp
	mv ${conf_dir}/${U2UP_NETWORK_CONF_FILE}_tmp ${conf_dir}/${U2UP_NETWORK_CONF_FILE}
	rv=$?
	echo "${var_net_config_current}=${value}"
	return $rv
}

enable_net_config_selection() {
	local rv=0
	local NET_INTERNAL_IFNAME_SET=""
	local NET_INTERNAL_ADDR_MASK_SET=""
	local NET_INTERNAL_GW_SET=""
	local NET_DNS_SET=""
	local NET_DOMAINS_SET=""
	local TARGET_DONE=0
	local new_target_done=${1:-0}
	local root_path_prefix=${2:-"/"}
	local conf_dir=${3:-${U2UP_CONF_DIR}}

	if [ "${root_path_prefix}" = "/" ]; then
		root_path_prefix=""
	fi

	if [ ! -f "${root_path_prefix}${conf_dir}/${U2UP_NETWORK_CONF_FILE}" ]; then
		return 1
	fi
	source ${root_path_prefix}${conf_dir}/${U2UP_NETWORK_CONF_FILE}
	if [ $TARGET_DONE -eq 0 ]; then
		if [ -n "${NET_INTERNAL_IFNAME_SET}" ] && [ -n "${NET_INTERNAL_ADDR_MASK_SET}" ] && [ -n "${NET_INTERNAL_GW_SET}" ]; then
			nmcli con add type ethernet con-name internal ifname ${NET_INTERNAL_IFNAME_SET} ip4 ${NET_INTERNAL_ADDR_MASK_SET} gw4 ${NET_INTERNAL_GW_SET}
			rv=$?
			if [ $rv -eq 0 ]; then
				nmcli con mod internal connection.zone trusted
				rv=$?
			fi
		fi
		if [ $rv -eq 0 ] && [ -n "${NET_DNS_SET}" ]; then
			nmcli con mod internal ipv4.dns "${NET_DNS_SET}"
			rv=$?
		fi
		if [ $rv -eq 0 ]; then
			set_target_done_for ${root_path_prefix}${conf_dir}/${U2UP_NETWORK_CONF_FILE} ${new_target_done}
			rv=$?
		fi
	fi
	return $rv
}

store_install_repo_selection() {
	local rv=1
	local var_install_repo_set=""
	local var_install_repo_current=""
	local conf_dir=${1}
	shift
	local value="$(echo $@ | sed 's/[^:]*://' | sed 's/ *//')"
	local name="$(echo $@ | sed 's/RENAMED //' | sed 's/:.*//')"

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ -z "${value}" ] || [ "x${name}" = "x${value}" ]; then
		return 0
	fi
	case $name in
	"Base URL")
		var_install_repo_set=INSTALL_REPO_BASE_URL_SET
		var_install_repo_current=install_repo_base_url_current
		;;
	*)
		return 1;
	esac

	cat ${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE} | grep -v "${var_install_repo_set}=" > ${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}_tmp
	echo "${var_install_repo_set}=$value" >> ${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}_tmp
	mv ${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}_tmp ${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}
	rv=$?
	echo "${var_install_repo_current}=${value}"
	return $rv
}

enable_install_repo_selection() {
	local rv=0
	local INSTALL_REPO_BASE_URL_SET=""
	local TARGET_DONE=0
	local new_target_done=${1:-0}
	local root_path_prefix=${2:-"/"}
	local conf_dir=${3:-${U2UP_CONF_DIR}}

	if [ "${root_path_prefix}" = "/" ]; then
		root_path_prefix=""
	fi

	if [ ! -f "${root_path_prefix}${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}" ]; then
		return 1
	fi
	source ${root_path_prefix}${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}
	if [ $TARGET_DONE -eq 0 ]; then
		if [ -n "${INSTALL_REPO_BASE_URL_SET}" ]; then
			mkdir -p ${root_path_prefix}/etc/yum.repos.d
			echo "[base-repo]" > ${root_path_prefix}/etc/yum.repos.d/base.repo
			echo "name=Base installation repository" >> ${root_path_prefix}/etc/yum.repos.d/base.repo
			echo "baseurl=${INSTALL_REPO_BASE_URL_SET}" >> ${root_path_prefix}/etc/yum.repos.d/base.repo
			echo "enabled=1" >> ${root_path_prefix}/etc/yum.repos.d/base.repo
			echo "metadata_expire=0" >> ${root_path_prefix}/etc/yum.repos.d/base.repo
			echo "gpgcheck=0" >> ${root_path_prefix}/etc/yum.repos.d/base.repo
			set_target_done_for ${root_path_prefix}${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE} ${new_target_done}
			rv=$?
		else
			rm -rf /etc/yum.repos.d
			rv=$?
		fi
	fi
	return $rv
}

prepare_u2up_upgrade_configuration() {
	local rv=0
	local conf_dir=$1

	if [ -z "${conf_dir}" ]; then
		return 1
	fi
	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ ! -e "${conf_dir}/${U2UP_KEYMAP_CONF_FILE}" ]; then
		cp -pf ${U2UP_CONF_DIR}/${U2UP_KEYMAP_CONF_FILE} ${conf_dir}/
		(( rv+=$? ))
	fi
	if [ ! -e "${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}" ]; then
		cp -pf ${U2UP_CONF_DIR}/${U2UP_TARGET_DISK_CONF_FILE} ${conf_dir}/
		(( rv+=$? ))
		source ${conf_dir}/${U2UP_TARGET_DISK_CONF_FILE}
		case ${TARGET_PART_SET} in
		${TARGET_DISK_SET}3)
			upgrade_disk_part=4
			;;
		${TARGET_DISK_SET}4)
			upgrade_disk_part=3
			;;
		esac
		store_target_part_selection ${TARGET_DISK_SET}${upgrade_disk_part} ${conf_dir}
		(( rv+=$? ))
	fi
	if [ ! -e "${conf_dir}/${U2UP_TARGET_HOSTNAME_CONF_FILE}" ]; then
		cp -pf ${U2UP_CONF_DIR}/${U2UP_TARGET_HOSTNAME_CONF_FILE} ${conf_dir}/
		(( rv+=$? ))
	fi
	if [ ! -e "${conf_dir}/${U2UP_TARGET_ADMIN_CONF_FILE}" ]; then
		cp -pf ${U2UP_CONF_DIR}/${U2UP_TARGET_ADMIN_CONF_FILE} ${conf_dir}/
		(( rv+=$? ))
	fi
	if [ ! -e "${conf_dir}/${U2UP_NETWORK_CONF_FILE}" ]; then
		cp -pf ${U2UP_CONF_DIR}/${U2UP_NETWORK_CONF_FILE} ${conf_dir}/
		(( rv+=$? ))
	fi
	if [ ! -e "${conf_dir}/${U2UP_INSTALL_REPO_CONF_FILE}" ]; then
		cp -pf ${U2UP_CONF_DIR}/${U2UP_INSTALL_REPO_CONF_FILE} ${conf_dir}/
		(( rv+=$? ))
	fi
	return $rv
}

populate_u2up_configurations() {
	local root_path_prefix=$1
	local conf_dir=${2:-${U2UP_CONF_DIR}}
	local file=""
	local rv=1

	if [ ! -d "${conf_dir}" ]; then
		return 1
	fi
	if [ -z "$root_path_prefix" ]; then
		return $rv
	fi
	rm -rf ${root_path_prefix}${U2UP_CONF_DIR}
	mkdir -p $(dirname ${root_path_prefix}${U2UP_CONF_DIR})
	cp -a ${conf_dir} ${root_path_prefix}${U2UP_CONF_DIR}
	rv=$?
	if [ $rv -eq 0 ]; then
		for file in $(ls ${root_path_prefix}${U2UP_CONF_DIR}); do
			set_target_done_for ${root_path_prefix}${U2UP_CONF_DIR}/${file} 0
			rv=$?
		done
	fi
	return $rv
}

#
# Finalize configuration during the first boot.
# (used in "u2up-pre-config.sh")
#
evaluate_u2up_configurations() {
#set -x
	local root_path_prefix="/"
	local file=""
	local rv=1
	if [ ! -d "${root_path_prefix}${U2UP_CONF_DIR}" ]; then
		return $rv
	fi
	rv=0
	for file in $(ls ${root_path_prefix}${U2UP_CONF_DIR}); do
		case $file in
		${U2UP_KEYMAP_CONF_FILE})
			enable_keymap_selection 1 ${root_path_prefix}
			rv=$?
			;;
		${U2UP_TARGET_DISK_CONF_FILE})
			;;
		${U2UP_TARGET_HOSTNAME_CONF_FILE})
			enable_target_hostname_selection 1 ${root_path_prefix}
			rv=$?
			;;
		${U2UP_TARGET_ADMIN_CONF_FILE})
			enable_target_admin_selection 1 ${root_path_prefix}
			rv=$?
			;;
		${U2UP_NETWORK_CONF_FILE})
			enable_net_config_selection 1 ${root_path_prefix}
			rv=$?
			;;
		${U2UP_INSTALL_REPO_CONF_FILE})
			enable_install_repo_selection 1 ${root_path_prefix}
			rv=$?
			;;
		esac
	done
	return $rv
}

